name       : libhangul
version    : 0.1.0
release    : 2
source     :
    - https://github.com/choehwanjin/libhangul/archive/libhangul-0.1.0.tar.gz : e2a81ef159ed098d3cc1a20377dba6204821b7ce2bc24cfb2f2543adf3bc5830
license    : LGPL-2.1-only
component  : desktop.core
summary    : A library to support hangul input method logic, hanja dictionary and small hangul character classification
description: |
    A library to support hangul input method logic, hanja dictionary and small hangul character classification
setup      : |
    %autogen --disable-static
    cp /usr/share/gettext/po/Makefile.in.in po/
build      : |
    %make -j1
install    : |
    %make_install
